function modelDat = importfile(filename, dataLines)
%IMPORTFILE1 Import data from a text file
%  S0 = IMPORTFILE1(FILENAME) reads data from text file FILENAME for the
%  default selection.  Returns the data as a table.
%
%  S0 = IMPORTFILE1(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  s0 = importfile("/project/3023009.03/scripts/Behavior/Computational modelling/TrialValues/Choice/HR/Base/s0.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Jun-2022 16:24:58

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 17);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["ppnr", "run", "trial", "choice", "action", "money", "shocks", "trialtype", "rt", "dHR", ...
    "money_s", "shocks_s", "EV", "EV_s", "dHR_s","trialnrs", "TrialVals"];
opts.VariableTypes = ["double", "double", "double", "categorical", "categorical", "double", "double", "categorical", "double", "double", ...
    "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["choice", "action", "trialtype"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "rt", "TrimNonNumeric", true);
opts = setvaropts(opts, "rt", "ThousandsSeparator", ",");

% Import the data
modelDat = readtable(filename, opts);

end