function data = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  GAMEDATA8881212025 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  GAMEDATA8881212025 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  data = importfile("yourPath\sub-001\behav\game_data_sub-001.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Feb-2025 15:24:43

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 56);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Totalscore", "trialNumber", "PredatorType", "PredatorName", "Predator_x", "Predator_y", "PredatorAngle", "PredatorMean", "PredatorStd", "PredatorSpeed", "torchMoved", "torchON", "torch_x", "torch_y", "torchAngle", "playerAngle", "torchSize", "RTInitiation", "RTConfirmation", "RTTorchON", "PredictionError", "HitMiss", "ChangePoint", "PredatorAttackTime", "LivesLeft", "NoiseLevel", "HeadPhoneCheckPassFail", "HeadPhoneCheckScore", "HeadPhonePassThreshold", "TimestampPredatorPlayerCollision", "TimestampTorchPlayerCollision", "TimestampOutcome", "TimestampPredatorWarning", "TimestampTrialStart", "TimestampWaitSceneCall", "TimestampITICall", "TimestampPredatorPlayerCollision_locked", "TimestampTorchPlayerCollision_locked", "TimestampOutcome_locked", "TimestampPredatorWarning_locked", "TimestampTrialStart_locked", "TimestampWaitSceneCall_locked", "TimestampITICall_locked", "WaitJitter", "ITIJitter", "subjectID", "date", "time", "Discontinued", "MaxTrials", "BlockNumber", "HighScore", "ScoreNormalized", "TrackMouse_x", "TrackMouse_y", "TrainingQuiz"];
opts.VariableTypes = ["double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "categorical", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "datetime", "datetime", "double", "categorical", "double", "double", "double", "categorical", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["PredatorName", "RTTorchON", "HeadPhoneCheckPassFail", "HeadPhoneCheckScore", "HeadPhonePassThreshold", "TimestampPredatorPlayerCollision", "TimestampPredatorPlayerCollision_locked", "MaxTrials", "TrackMouse_x", "TrackMouse_y", "TrainingQuiz"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "date", "InputFormat", "dd.MM.yyyy");
opts = setvaropts(opts, "time", "InputFormat", "HH:mm:ss");

% Import the data
data = readtable(filename, opts);

end